source 'https://rubygems.org'
gem 'grape'
gem 'activerecord'
gem 'active_model_serializers', git: 'https://github.com/rails-api/active_model_serializers.git'
gem 'grape-active_model_serializers', git: 'git@github.com:jrhe/grape-active_model_serializers.git'
